import random

# List of irregular verbs with their past simple and past participle forms
irregular_verbs = [
    {"base": "go", "past_simple": "went", "past_participle": "gone"},
    {"base": "burn", "past_simple": "burn", "past_participle": "burn"},
    {"base": "burst", "past_simple": "burst", "past_participle": "burst"},
    {"base": "bust", "past_simple": "bust", "past_participle": "bust"},
    {"base": "cast", "past_simple": "cast", "past_participle": "cast"},
    {"base": "cost", "past_simple": "cost", "past_participle": "cost"},
    {"base": "cut", "past_simple": "cut", "past_participle": "cut"},
    {"base": "fit", "past_simple": "fit", "past_participle": "fit"},
    {"base": "shed", "past_simple": "shed", "past_participle": "shed"},
    {"base": "put", "past_simple": "put", "past_participle": "put"},
    {"base": "sublet", "past_simple": "sublet", "past_participle": "sublet"},
    {"base": "rid", "past_simple": "rid", "past_participle": "rid"},
    {"base": "hurt", "past_simple": "hurt", "past_participle": "hurt"},
    {"base": "knit", "past_simple": "knit", "past_participle": "knit"},
    {"base": "spread", "past_simple": "spread", "past_participle": "spread"},
    {"base": "wed", "past_simple": "wed", "past_participle": "wed"},
    {"base": "wet", "past_simple": "wet", "past_participle": "wet"},
    {"base": "bet", "past_simple": "bet", "past_participle": "bet"},
    {"base": "beat", "past_simple": "beat", "past_participle": "beaten"},
    {"base": "become", "past_simple": "became", "past_participle": "become"},
    {"base": "begin", "past_simple": "began", "past_participle": "begun"},
    {"base": "feel", "past_simple": "felt", "past_participle": "felt"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    {"base": "eat", "past_simple": "ate", "past_participle": "eaten"},
    # Add more verbs as needed
]

def irregular_verb_quiz():
    # Shuffle the list of irregular verbs
    random.shuffle(irregular_verbs)

    # Initialize score
    score = 0

    for verb in irregular_verbs:
        # Display the base form of the verb
        print(f"\nBase form: {verb['base']}")

        # Get user input for past simple and past participle forms
        user_past_simple = input("Past Simple: ").strip().lower()
        user_past_participle = input("Past Participle: ").strip().lower()

        # Check user input against the correct forms
        if user_past_simple == verb["past_simple"].lower() and user_past_participle == verb["past_participle"].lower():
            print("Correct!")
            score += 1
        else:
            print(f"Wrong! The correct forms are: {verb['past_simple']} (Past Simple) and {verb['past_participle']} (Past Participle)")

    # Display final score
    print(f"\nGame Over! Your final score is {score}/{len(irregular_verbs)}.")

if __name__ == "__main__":
    print("Welcome to the Irregular Verb Quiz!")
    irregular_verb_quiz()
